/// Generated by AssetsRefGenerator on 2021/08/26
class Res {
  static const String dumbbell = "assets/images/dumbbell.png";
  static const String endorder = "assets/images/endorder.png";
  static const String facebook = "assets/images/facebook.png";
  static const String fav = "assets/images/fav.png";
  static const String favoff = "assets/images/favoff.png";
  static const String inprogressorder = "assets/images/inprogressorder.png";
  static const String instagram = "assets/images/instagram.png";
  static const String jacket = "assets/images/jacket.png";
  static const String leader = "assets/images/leader.png";
  static const String logo = "assets/images/logo.png";
  static const String neworder = "assets/images/neworder.png";
  static const String neworderk = "assets/images/neworderk.png";
  static const String profile = "assets/images/profile.png";
  static const String returns = "assets/images/returns.png";
  static const String saudi_arabia  = "assets/images/saudi-arabia .png";
  static const String shippingorder = "assets/images/shippingorder.png";
  static const String shoes = "assets/images/shoes.png";
  static const String shop = "assets/images/shop.png";
  static const String sucesspay = "assets/images/sucesspay.png";
  static const String trousers = "assets/images/trousers.png";
  static const String tshirt = "assets/images/tshirt.png";
  static const String twitter = "assets/images/twitter.png";
  static const String uk  = "assets/images/uk .png";
  static const String watch = "assets/images/watch.png";
  static const String whatsapp = "assets/images/whatsapp.png";
}
